spring:
  application:
    name: service-consumer
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8100
number:
  service:
    url: http://localhost:8080/random
# microservice-a:
 # ribbon:
 #   listOfServers: localhost:8080,localhost:8081
 
      
